version: '3'

services:
  quanlyduan:
    container_name: quanlyduan
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db-data:/app/user/db/
      - uploads:/app/user/public/uploads/
    ports:
        - 80:3000
    command: ["rails", "server"]
volumes:
  db-data:
  uploads:
